version: "3.8"

services:
  backend:
    build: .
    container_name: shopee-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/liennganhmoi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - FILE_UPLOAD_DIR=/app/uploads
    depends_on:
      - db
    networks:
      - shopee-network
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./shopee-frontend
    container_name: shopee-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - shopee-network

  db:
    image: postgres:16-alpine
    container_name: shopee-db
    environment:
      - POSTGRES_DB=liennganhmoi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./plaindata.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shopee-network

networks:
  shopee-network:
    driver: bridge

volumes:
  db-data:
