version: "3.8"

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - shopee-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  backend:
    build: .
    container_name: shopee-backend
    restart: on-failure
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/liennganhmoi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - FILE_UPLOAD_DIR=/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shopee-network
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./shopee-frontend
    container_name: shopee-frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - shopee-network

  db:
    image: postgres:16-alpine
    container_name: shopee-db
    environment:
      - POSTGRES_DB=liennganhmoi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./plaindata.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d liennganhmoi"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - shopee-network

networks:
  shopee-network:
    driver: bridge

volumes:
  db-data:
